name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "docker-compose.yaml"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

concurrency:
  group: climbge-backend
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            export REPO_SSH_URL=${{ secrets.REPO_SSH_URL }}
            bash -lc '/app/deploy.sh'
